app.payment.auto-confirm-enabled=false
app.payment.imap.enabled=false
app.payment.imap.host=imap.gmail.com
app.payment.imap.port=993
app.payment.imap.poll-delay=30000
app.payment.imap.username=${PAYMENT_IMAP_USERNAME:}
app.payment.imap.password=${PAYMENT_IMAP_PASSWORD:}
app.payment.imap.test-senders=${PAYMENT_IMAP_TEST_SENDERS:}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
