spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lunaris_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

whatsapp:
  phone-number-id: 1160685710458679
  access-token:  EAAOpuc7IAZCYBRuPrBtTulbRW7aEHeZBZCBnLd2f3cZCxEHoo9xgQXiCrvY7fOoZBZAViOvYHZB2dtpA2Tqf4GHdSKO9O8M8MZAnBrHZA4bdGklMIEpYZCSaZBZAwk9NdWvFBtU3PcqMK6lhYjsZAA6qwOqavHNhwp7SZAPo14AsTGBGjcLHEXl2ughAjlABuGZCtnTjY9OP9h9GqJsdXm3ZBPk0HbwmxqZA8Li7uiIiZCYAR9hTAZAQnRHk9fv9fMFf3hf416buRhWlulgCZAXhtsAS5MLWGSfDfgZDZD


storage:
  local-dir: /home/ignacio/Documentos/lunaris-ansenuza/comprobantes/

server:
  port: 8080