spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lunaris_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

whatsapp:
  phone-number-id: 1160685710458679
  access-token:  EAAOpuc7IAZCYBRpZBQzJcEHPV0rygfZAKY9dWghZCCjANTfge1TJAgOYmiOYNH2x24aiouGPL3mxMacDkMcnZB2tH7QV4RnGB0Aij9pplOIDWcvxEmuXUh1uGv20eI7KF7Mv02EAdZCd6fjtbTzQfN5QG6OkM1vZBPFJj2cMHwokuQcGC3AbZAdz2rYNmB677f3ARJbYZC9c0K5WMs2Q9SW7yIRPaikVaQhgpctYUuZB7FoITbC0xX0jw52gPZCAhQdS6ZCDXAWsJ4fppiTfM2X9Q1zHcQZDZD


server:
  port: 8080