app.payment.auto-confirm-enabled=false
app.payment.imap.enabled=false
app.payment.imap.host=imap.gmail.com
app.payment.imap.port=993
app.payment.imap.poll-delay=30000
app.payment.imap.username=${PAYMENT_IMAP_USERNAME:}
app.payment.imap.password=${PAYMENT_IMAP_PASSWORD:}
app.payment.imap.test-senders=${PAYMENT_IMAP_TEST_SENDERS:}
