package com.lunaris.ansenuza.application.telemetry;

public enum ChatbotEventType {
    SESSION_STARTED, MESSAGE_RECEIVED, STEP_CHANGED, PASSENGER_IDENTIFIED, DRIVER_IDENTIFIED,
    BOOKING_STARTED, PRICE_REQUESTED, PRICE_SENT, ROUTE_SELECTED, DATE_SELECTED,
    PASSENGER_DATA_COMPLETED, SUMMARY_SENT, BOOKING_CREATED, BOOKING_DECLINED,
    SESSION_EXPIRED, HUMAN_HANDOFF, WAITLISTED, FLOW_BLOCKED, INPUT_REJECTED, SEND_FAILED
}

