INSERT INTO localities (name) VALUES
('San Guillermo'),
('Suardi'),
('Villa Trinidad'),
('Arrufó'),
('Morteros'),
('Brinkmann'),
('Porteña'),
('Seeber'),
('La Paquita'),
('Balnearia'),
('Miramar'),
('Marull'),
('Altos de Chipión'),
('Colonia Vignaud'),
('Freyre'),
('Devoto'),
('San Francisco'),
('Las Varillas'),
('Arroyito'),
('Rafaela'),
('Sunchales'),
('Córdoba'),
('Aeropuerto Córdoba')
ON CONFLICT (name) DO NOTHING;